const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/01.mp3",
    "image": "images/01.png",
    "transcript": "圖片裡有幾個學生？\n(A) 三個\n(B) 四個\n(C) 七個",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/02.mp3",
    "image": "images/02.png",
    "transcript": "這個人在做什麼運動？\n(A) 他在打籃球\n(B) 他在打網球\n(C) 他在打棒球",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/03.mp3",
    "image": "images/03.png",
    "transcript": "請問小美喜歡做什麼？\n(A) 她喜歡打掃\n(B) 她喜歡做菜\n(C) 她喜歡洗衣服",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/04.mp3",
    "image": "images/04.png",
    "transcript": "弟弟今天怎麼沒去上課？\n(A) 他腳痛\n(B) 他頭痛\n(C) 他肚子痛",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/05.mp3",
    "image": "images/05.png",
    "transcript": "小明給美美什麼？\n(A) 水果\n(B) 蛋糕\n(C) 餃子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/06.mp3",
    "image": "images/06.png",
    "transcript": "老師在做什麼？\n(A) 老師在寫字\n(B) 老師在唱歌\n(C) 老師在看書",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/07.mp3",
    "image": "images/07.png",
    "transcript": "這些人在哪裡？\n(A) 在餐廳\n(B) 在教室\n(C) 在圖書館",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/08.mp3",
    "image": "images/08.png",
    "transcript": "桌子上有什麼？\n(A) 書\n(B) 筆\n(C) 鞋子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/09.mp3",
    "image": "images/09.png",
    "transcript": "爸爸在做什麼？\n(A) 他在看報紙\n(B) 他在看電影\n(C) 他在看電視",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/10.mp3",
    "image": "images/10.png",
    "transcript": "他們在吃什麼？\n(A) 水果\n(B) 餅乾\n(C) 麵條",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 11,
    "part": 2,
    "question": "",
    "audio": "sounds/11.mp3",
    "image": "",
    "transcript": "對話\n女：小王，這件衣服是誰的？\n男：是我妹妹的。\n問：衣服是誰的？\n(A) 小王的\n(B) 小王妹妹的\n(C) 小王媽媽的",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 12,
    "part": 2,
    "question": "",
    "audio": "sounds/12.mp3",
    "image": "",
    "transcript": "對話\n男：你昨天去看電影了嗎？\n女：沒有，我去打球了。\n問：昨天這個女的是做什麼？\n(A) 她去打球\n(B) 她去看電影\n(C) 她去唱歌",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 13,
    "part": 2,
    "question": "",
    "audio": "sounds/13.mp3",
    "image": "",
    "transcript": "對話\n女：你最喜歡吃什麼水果？\n男：我最喜歡吃香蕉。\n問：這個男生最喜歡吃什麼？\n(A) 蘋果\n(B) 香蕉\n(C) 葡萄",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 14,
    "part": 2,
    "question": "",
    "audio": "sounds/14.mp3",
    "image": "",
    "transcript": "對話\n男：這件衣服多少錢？\n女：五百塊。\n問：這件衣服多少錢？\n(A) 300塊\n(B) 500塊\n(C) 800塊",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 15,
    "part": 2,
    "question": "",
    "audio": "sounds/15.mp3",
    "image": "",
    "transcript": "對話\n女：你怎麼了？\n男：我頭很痛。\n問：這個男的哪裡不舒服？\n(A) 腳\n(B) 頭\n(C) 肚子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 16,
    "part": 2,
    "question": "",
    "audio": "sounds/16.mp3",
    "image": "",
    "transcript": "對話\n男：你要喝茶嗎？\n女：不用了，謝謝。\n問：女的要喝茶嗎？\n(A) 要\n(B) 不要\n(C) 喜歡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 17,
    "part": 2,
    "question": "",
    "audio": "sounds/17.mp3",
    "image": "",
    "transcript": "對話\n女：你有沒有哥哥？\n男：有一個。\n問：這個男的有幾個哥哥？\n(A) 一個\n(B) 兩個\n(C) 三個",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 18,
    "part": 2,
    "question": "",
    "audio": "sounds/18.mp3",
    "image": "",
    "transcript": "對話\n男：你會不會說日文？\n女：不會。\n問：女的會不會說日文？\n(A) 會\n(B) 不會\n(C) 喜歡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 19,
    "part": 2,
    "question": "",
    "audio": "sounds/19.mp3",
    "image": "",
    "transcript": "對話\n女：你什麼時候去中國？\n男：下個月。\n問：男的什麼時候去中國？\n(A) 下星期\n(B) 下個月\n(C) 明年",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 20,
    "part": 2,
    "question": "",
    "audio": "sounds/20.mp3",
    "image": "",
    "transcript": "對話\n男：這本書是新的還是舊的？\n女：是新的。\n問：這本書是新的還是舊的？\n(A) 舊的\n(B) 新的\n(C) 貴的",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
   {
    "id": 21,
    "part": 2,
    "question": "",
    "audio": "sounds/21.mp3",
    "image": "",
    "transcript": "對話\n女：你常常去圖書館嗎？\n男：我每天都去。\n問：男的多久去一次圖書館？\n(A) 每天\n(B) 常常\n(C) 有時候",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 22,
    "part": 2,
    "question": "",
    "audio": "sounds/22.mp3",
    "image": "",
    "transcript": "對話\n男：你家住在哪裡？\n女：在學校旁邊。\n問：女的家在哪裡？\n(A) 學校旁邊\n(B) 公園旁邊\n(C) 醫院旁邊",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 23,
    "part": 2,
    "question": "",
    "audio": "sounds/23.mp3",
    "image": "",
    "transcript": "對話\n女：你喜歡哪種顏色？\n男：我喜歡藍色。\n問：男的喜歡什麼顏色？\n(A) 紅色\n(B) 藍色\n(C) 綠色",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 24,
    "part": 2,
    "question": "",
    "audio": "sounds/24.mp3",
    "image": "",
    "transcript": "對話\n男：這個地方可以抽菸嗎？\n女：不可以。\n問：這個地方可以抽菸嗎？\n(A) 可以\n(B) 不可以\n(C) 喜歡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 25,
    "part": 2,
    "question": "",
    "audio": "sounds/25.mp3",
    "image": "",
    "transcript": "對話\n女：你會游泳嗎？\n男：會，可是游得不太好。\n問：男的會不會游泳？\n(A) 不會\n(B) 會\n(C) 喜歡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 26,
    "part": 2,
    "question": "",
    "audio": "sounds/26.mp3",
    "image": "",
    "transcript": "對話\n男：明天要不要一起去買東西？\n女：好啊。\n問：他們明天要做什麼？\n(A) 去買東西\n(B) 去看電影\n(C) 去打球",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 27,
    "part": 2,
    "question": "",
    "audio": "sounds/27.mp3",
    "image": "",
    "transcript": "對話\n女：你幾點去上班？\n男：八點。\n問：男的幾點去上班？\n(A) 七點\n(B) 八點\n(C) 九點",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 28,
    "part": 2,
    "question": "",
    "audio": "sounds/28.mp3",
    "image": "",
    "transcript": "對話\n男：這個菜是誰做的？\n女：我媽媽做的。\n問：這個菜是誰做的？\n(A) 爸爸\n(B) 媽媽\n(C) 哥哥",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 29,
    "part": 2,
    "question": "",
    "audio": "sounds/29.mp3",
    "image": "",
    "transcript": "對話\n女：你喜歡看電視嗎？\n男：不太喜歡，我比較喜歡看書。\n問：男的喜歡什麼？\n(A) 看電視\n(B) 看書\n(C) 玩電腦",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 30,
    "part": 2,
    "question": "",
    "audio": "sounds/30.mp3",
    "image": "",
    "transcript": "對話\n男：你想去哪裡玩？\n女：我想去海邊。\n問：女的想去哪裡？\n(A) 山上\n(B) 海邊\n(C) 公園",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 31,
    "part": 3,
    "question": "",
    "audio": "sounds/31.mp3",
    "image": "",
    "transcript": "敘述\n昨天晚上下雨，所以我沒有出去。\n問：昨天晚上為什麼沒出去？\n(A) 因為下雨\n(B) 因為生病\n(C) 因為作業多",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 32,
    "part": 3,
    "question": "",
    "audio": "sounds/32.mp3",
    "image": "",
    "transcript": "敘述\n小王每天早上六點起床，七點去上學。\n問：小王幾點起床？\n(A) 六點\n(B) 七點\n(C) 八點",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 33,
    "part": 3,
    "question": "",
    "audio": "sounds/33.mp3",
    "image": "",
    "transcript": "敘述\n我喜歡冬天，因為冬天可以滑雪。\n問：我為什麼喜歡冬天？\n(A) 因為可以滑雪\n(B) 因為可以游泳\n(C) 因為可以看花",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 34,
    "part": 3,
    "question": "",
    "audio": "sounds/34.mp3",
    "image": "",
    "transcript": "敘述\n小李有兩個哥哥，一個姐姐。\n問：小李有幾個哥哥？\n(A) 一個\n(B) 兩個\n(C) 三個",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 35,
    "part": 3,
    "question": "",
    "audio": "sounds/35.mp3",
    "image": "",
    "transcript": "敘述\n今天星期天，學校沒有課。\n問：今天星期幾？\n(A) 星期五\n(B) 星期六\n(C) 星期天",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 36,
    "part": 3,
    "question": "",
    "audio": "sounds/36.mp3",
    "image": "",
    "transcript": "敘述\n王老師教我們中文。\n問：王老師教什麼？\n(A) 英文\n(B) 中文\n(C) 數學",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 37,
    "part": 3,
    "question": "",
    "audio": "sounds/37.mp3",
    "image": "",
    "transcript": "敘述\n這家餐廳的菜很好吃，所以人很多。\n問：為什麼人很多？\n(A) 因為便宜\n(B) 因為菜好吃\n(C) 因為地方大",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 38,
    "part": 3,
    "question": "",
    "audio": "sounds/38.mp3",
    "image": "",
    "transcript": "敘述\n小張昨天去買了一雙鞋子。\n問：小張昨天買了什麼？\n(A) 衣服\n(B) 鞋子\n(C) 帽子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 39,
    "part": 3,
    "question": "",
    "audio": "sounds/39.mp3",
    "image": "",
    "transcript": "敘述\n這家店星期一休息。\n問：這家店星期幾休息？\n(A) 星期天\n(B) 星期一\n(C) 星期六",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 40,
    "part": 3,
    "question": "",
    "audio": "sounds/40.mp3",
    "image": "",
    "transcript": "敘述\n小王的電腦壞了，不能用。\n問：小王的什麼壞了？\n(A) 手機\n(B) 電腦\n(C) 電視",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 41,
    "part": 4,
    "question": "",
    "audio": "sounds/41.mp3",
    "image": "",
    "transcript": "敘述\n昨天我去醫院看朋友。\n問：昨天我去哪裡？\n(A) 公園\n(B) 醫院\n(C) 學校",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 42,
    "part": 4,
    "question": "",
    "audio": "sounds/42.mp3",
    "image": "",
    "transcript": "敘述\n今天早上我吃了一個麵包。\n問：今天早上我吃了什麼？\n(A) 蘋果\n(B) 麵包\n(C) 魚",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 43,
    "part": 4,
    "question": "",
    "audio": "sounds/43.mp3",
    "image": "",
    "transcript": "敘述\n我昨天買了一本新書，很有意思。\n問：我昨天買了什麼？\n(A) 書\n(B) 鞋子\n(C) 衣服",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 44,
    "part": 4,
    "question": "",
    "audio": "sounds/44.mp3",
    "image": "",
    "transcript": "敘述\n我們學校有三個圖書館。\n問：學校有幾個圖書館？\n(A) 一個\n(B) 兩個\n(C) 三個",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 45,
    "part": 4,
    "question": "",
    "audio": "sounds/45.mp3",
    "image": "",
    "transcript": "敘述\n哥哥喜歡打籃球，每天都去打。\n問：哥哥喜歡做什麼？\n(A) 打籃球\n(B) 打網球\n(C) 游泳",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/46.mp3",
    "image": "",
    "transcript": "敘述\n今天下雪了，外面很冷。\n問：今天的天氣怎麼樣？\n(A) 很熱\n(B) 很冷\n(C) 很舒服",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/47.mp3",
    "image": "",
    "transcript": "敘述\n我家前面有一個公園。\n問：我家前面有什麼？\n(A) 公園\n(B) 學校\n(C) 醫院",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/48.mp3",
    "image": "",
    "transcript": "敘述\n這杯咖啡很甜，不太好喝。\n問：這杯咖啡怎麼樣？\n(A) 很甜\n(B) 很苦\n(C) 很鹹",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/49.mp3",
    "image": "",
    "transcript": "敘述\n他昨天買了一台新手機。\n問：他昨天買了什麼？\n(A) 電腦\n(B) 手機\n(C) 電視",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/50.mp3",
    "image": "",
    "transcript": "敘述\n明天我們要去動物園看動物。\n問：明天我們要去哪裡？\n(A) 公園\n(B) 動物園\n(C) 博物館",
    "options": ["(A)", "(B)", "(C)", "(D)"],
    "answer": "D",
    "remark": ""
  }
];