const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/01.mp3",
    "image": "images/01.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/02.mp3",
    "image": "images/02.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/03.mp3",
    "image": "images/03.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/04.mp3",
    "image": "images/04.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/05.mp3",
    "image": "images/05.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/06.mp3",
    "image": "images/06.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/07.mp3",
    "image": "images/07.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/08.mp3",
    "image": "images/08.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/09.mp3",
    "image": "images/09.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/10.mp3",
    "image": "images/10.png",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 11,
    "part": 2,
    "question": "",
    "audio": "sounds/11.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 12,
    "part": 2,
    "question": "",
    "audio": "sounds/12.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 13,
    "part": 2,
    "question": "",
    "audio": "sounds/13.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 14,
    "part": 2,
    "question": "",
    "audio": "sounds/14.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 15,
    "part": 2,
    "question": "",
    "audio": "sounds/15.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 16,
    "part": 2,
    "question": "",
    "audio": "sounds/16.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 17,
    "part": 2,
    "question": "",
    "audio": "sounds/17.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 18,
    "part": 2,
    "question": "",
    "audio": "sounds/18.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 19,
    "part": 2,
    "question": "",
    "audio": "sounds/19.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 20,
    "part": 2,
    "question": "",
    "audio": "sounds/20.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
   {
    "id": 21,
    "part": 2,
    "question": "",
    "audio": "sounds/21.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 22,
    "part": 2,
    "question": "",
    "audio": "sounds/22.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 23,
    "part": 2,
    "question": "",
    "audio": "sounds/23.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 24,
    "part": 2,
    "question": "",
    "audio": "sounds/24.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 25,
    "part": 2,
    "question": "",
    "audio": "sounds/25.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 26,
    "part": 2,
    "question": "",
    "audio": "sounds/26.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 27,
    "part": 2,
    "question": "",
    "audio": "sounds/27.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 28,
    "part": 2,
    "question": "",
    "audio": "sounds/28.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 29,
    "part": 2,
    "question": "",
    "audio": "sounds/29.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 30,
    "part": 2,
    "question": "",
    "audio": "sounds/30.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 31,
    "part": 3,
    "question": "",
    "audio": "sounds/31.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 32,
    "part": 3,
    "question": "",
    "audio": "sounds/32.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 33,
    "part": 3,
    "question": "",
    "audio": "sounds/33.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 34,
    "part": 3,
    "question": "",
    "audio": "sounds/34.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 35,
    "part": 3,
    "question": "",
    "audio": "sounds/35.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 36,
    "part": 3,
    "question": "",
    "audio": "sounds/36.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 37,
    "part": 3,
    "question": "",
    "audio": "sounds/37.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 38,
    "part": 3,
    "question": "",
    "audio": "sounds/38.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 39,
    "part": 3,
    "question": "",
    "audio": "sounds/39.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 40,
    "part": 3,
    "question": "",
    "audio": "sounds/40.mp3",
    "image": "",
    "transcript": "",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 41,
    "part": 4,
    "question": "",
    "audio": "sounds/41.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）因為他想睡覺", "（B）因為他想運動", "（C）因為他不想上班", "（D）因為他起不了床"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 42,
    "part": 4,
    "question": "",
    "audio": "sounds/42.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她旅行時不小心掉了東西", "（B）她旅行時有些想去的地方沒去", "（C）她覺得旅行時最麻煩的是交通", "（D）她覺得旅行最重要的是風景漂亮"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 43,
    "part": 4,
    "question": "",
    "audio": "sounds/43.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她怕考得不好", "（B）她的成績不好", "（C）她沒參加考試", "（D）她怕題目寫不完"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 44,
    "part": 4,
    "question": "",
    "audio": "sounds/44.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）想請他搬家", "（B）想請他吃飯", "（C）介紹女朋友給他", "（D）請他注意聲音的大小"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 45,
    "part": 4,
    "question": "",
    "audio": "sounds/45.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她習慣在不同的時間睡覺", "（B）她每天都是這個時間起床", "（C）她認為睡覺對健康有影響", "（D）她不覺得自己很晚才睡覺"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/46.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）他剛從海邊回來", "（B）他喜歡夏天去海邊玩", "（C）他給這位小姐買了褲子", "（D）他約了這位小姐明天去運動"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/47.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她不想請這位先生吃蛋糕", "（B）她想幫這位先生慶祝生日", "（C）她要朋友來參加舞會就好", "（D）她想要大家一起唱生日歌"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/48.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她想拿商店送的東西", "（B）她最近很想花錢買東西", "（C）她想要這位先生送她禮物", "（D）她想和這位先生一起去逛街"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/49.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）這位先生今天想留在家裡", "（B）這位小姐怕自己太晚回家", "（C）他們兩人今天都想看棒球比賽", "（D）他們已經買完衣服回家休息了"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/50.mp3",
    "image": "",
    "transcript": "",
    "options": ["（A）她要把錢還給客人", "（B）東西賣出去就不能換了", "（C）她沒有東西可以換給客人", "(D)"],
    "answer": "（D）沒有發票，就不能換東西",
    "remark": ""
  }
];