const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/01.mp3",
    "image": "images/01.png",
    "transcript": "圖片裡有幾個學生？\n(A) 三個\n(B) 四個\n(C) 七個",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/02.mp3",
    "image": "images/02.png",
    "transcript": "提問 這個人在做什麼運動？\n(A) 他在打籃球\n(B) 他在打網球\n(C) 他在打棒球",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/03.mp3",
    "image": "images/03.png",
    "transcript": "提問 請問小美喜歡做什麼？\n(A) 她喜歡打掃\n(B) 她喜歡做菜\n(C) 她喜歡洗衣服",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/04.mp3",
    "image": "images/04.png",
    "transcript": "提問 弟弟今天怎麼沒去上課？\n(A) 他腳痛\n(B) 他頭痛\n(C) 他肚子痛",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/05.mp3",
    "image": "images/05.png",
    "transcript": "提問 小明給美美什麼？\n(A) 水果\n(B) 蛋糕\n(C) 餃子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/06.mp3",
    "image": "images/06.png",
    "transcript": "提問 這位先生現在在做什麼？\n(A) 他在教室上網\n(B) 他在辦公室工作\n(C) 他在辦公室上網",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/07.mp3",
    "image": "images/07.png",
    "transcript": "提問 小女孩在做什麼？\n(A) 她在寄信\n(B) 她在寫信\n(C) 她在打電話",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/08.mp3",
    "image": "images/08.png",
    "transcript": "提問 圖片裡有什麼？\n(A) 一枝鉛筆和兩本字典\n(B) 一本字典和兩支毛筆\n(C) 一本雜誌和兩本課本",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/09.mp3",
    "image": "images/09.png",
    "transcript": "提問 他們在做什麼？\n(A) 他們一邊看電視，一邊吃東西\n(B) 他們一邊吃東西，一邊和狗玩\n(C) 他們一邊和狗玩，一邊看電視",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/10.mp3",
    "image": "images/10.png",
    "transcript": "提問 這裡有哪些動物？\n(A) 這裡都是馬\n(B) 這裡有馬也有牛\n(C) 這裡只有牛沒有馬",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 11,
    "part": 2,
    "question": "",
    "audio": "sounds/11.mp3",
    "image": "images/11.png",
    "transcript": "男 剛剛那個年輕人在飯店裡吃了什麼食物？\n女 他吃了一碗麵。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 12,
    "part": 2,
    "question": "",
    "audio": "sounds/12.mp3",
    "image": "images/12.png",
    "transcript": "女 你要不要去博物館？\n男 好啊！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 13,
    "part": 2,
    "question": "",
    "audio": "sounds/13.mp3",
    "image": "images/13.png",
    "transcript": "男 這是您的巧克力蛋糕，請問還需要什麼嗎？\n女 請再給我一個湯匙，我們要一起吃。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 14,
    "part": 2,
    "question": "",
    "audio": "sounds/14.mp3",
    "image": "images/14.png",
    "transcript": "女 我昨天打電話給你，你怎麼沒接電話？\n男 我的手機壞了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 15,
    "part": 2,
    "question": "",
    "audio": "sounds/15.mp3",
    "image": "images/15.png",
    "transcript": "男 哪一個是妳的妹妹？\n女 那個短頭髮，戴眼鏡的是我妹妹。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 16,
    "part": 2,
    "question": "",
    "audio": "sounds/16.mp3",
    "image": "images/16.png",
    "transcript": "女 這家店為什麼這麼多人在排隊？\n男 因為這裡的衣服很便宜，很多人來這裡買衣服。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 17,
    "part": 2,
    "question": "",
    "audio": "sounds/17.mp3",
    "image": "images/17.png",
    "transcript": "男 聽說這家店的牛排和漢堡很好吃，妳要試一試嗎？\n女 我不能吃肉，請幫我點一份青菜。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 18,
    "part": 2,
    "question": "",
    "audio": "sounds/18.mp3",
    "image": "images/18.png",
    "transcript": "男 媽媽，我找了客廳和房間，怎麼都沒看見我新買的小說？\n女 你昨天放在浴室裡了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 19,
    "part": 2,
    "question": "",
    "audio": "sounds/19.mp3",
    "image": "images/19.png",
    "transcript": "女 我上次送你的畫你放在哪裡了？\n男 我把它掛在冰箱後面的牆上了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 20,
    "part": 2,
    "question": "",
    "audio": "sounds/20.mp3",
    "image": "images/20.png",
    "transcript": "男 聽說小美要表演，是鋼琴表演嗎？\n女 她以前表演過鋼琴，但是這次是吉他表演。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 21,
    "part": 2,
    "question": "",
    "audio": "sounds/21.mp3",
    "image": "images/21.png",
    "transcript": "女 已經晚上九點了，辦公室裡怎麼還有人？\n男 是蘇經理和小蔡，他們兩個還在開會。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 22,
    "part": 2,
    "question": "",
    "audio": "sounds/22.mp3",
    "image": "images/22.png",
    "transcript": "男 他們兩個人都很生氣，不知道他們在說什麼？\n女 他們一討論小孩的事情，就會不太開心。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 23,
    "part": 2,
    "question": "",
    "audio": "sounds/23.mp3",
    "image": "images/23.png",
    "transcript": "女 為什麼他今天沒來上班？\n男 因為他在家裡準備明天的報告。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 24,
    "part": 2,
    "question": "",
    "audio": "sounds/24.mp3",
    "image": "images/24.png",
    "transcript": "女 你們在山上新租的房子怎麼樣？\n男 房子很不錯。樓下房間有一個大窗戶。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 25,
    "part": 2,
    "question": "",
    "audio": "sounds/25.mp3",
    "image": "images/25.png",
    "transcript": "男 美美，我的那件短袖襯衫呢？\n女 我剛洗好，現在還沒乾喔！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
   {
    "id": 26,
    "part": 2,
    "question": "",
    "audio": "sounds/26.mp3",
    "image": "images/26.png",
    "transcript": "男 聽說小明家附近的風景很漂亮，是嗎？\n女 是啊！但是那裡冬天的溫度很低，你去找他要穿暖一點。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 27,
    "part": 2,
    "question": "",
    "audio": "sounds/27.mp3",
    "image": "images/27.png",
    "transcript": "女 你覺得認識臺灣最好的方法是什麼？\n男 看書、看電視介紹都不錯，但是最好的方法就是你自己去旅行。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 28,
    "part": 2,
    "question": "",
    "audio": "sounds/28.mp3",
    "image": "images/28.png",
    "transcript": "男 小美，你的新家怎麼樣？\n女 別說了，我搬到公寓去，結果樓上的小孩經常往下丟垃圾，環境非常髒。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 29,
    "part": 2,
    "question": "",
    "audio": "sounds/29.mp3",
    "image": "images/29.png",
    "transcript": "男 我們等一下三點在書店門口前見面嗎？\n女 我覺得有一點晚，我們可以早半個小時嗎？\n男 好啊，那一樣在書店門口前見嗎？\n女 對，書店門口見！\n男 請問他們幾點見面？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 30,
    "part": 2,
    "question": "",
    "audio": "sounds/30.mp3",
    "image": "images/30.png",
    "transcript": "男 請問妳要找什麼書？\n女 我正在找介紹日本風景的旅遊書。\n男 妳看到上面號碼了嗎？如果妳要找日本的書，那在中間 2 號。\n女 謝謝。\n男 請問介紹日本風景的書放在哪裡？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 31,
    "part": 3,
    "question": "",
    "audio": "sounds/31.mp3",
    "image": "images/31.png",
    "transcript": "男 來這家店的人真多。\n女 是啊！這家冰淇淋店有很多種味道的冰淇淋。\n男 我想吃巧克力和牛奶口味的，我們進去吃吧！\n女 好，我請客。\n男 請問他們等一下要做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 32,
    "part": 3,
    "question": "",
    "audio": "sounds/32.mp3",
    "image": "images/32.png",
    "transcript": "男 照片裡這些人是妳的家人嗎？你們在哪裡拍的？\n女 是啊，這是我的爸爸媽媽。這張照片是在船上拍的。\n男 這個戴帽子的人是誰？\n女 這是我爺爺。他已經七十歲了。\n男 請問他們說的是哪一張照片？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 33,
    "part": 3,
    "question": "",
    "audio": "sounds/33.mp3",
    "image": "images/33.png",
    "transcript": "男 要不要喝點兒啤酒？\n女 不行，我等一下要開車。\n男 那，喝點兒汽水吧？\n女 我還是喝茶好了。\n男 請問這位小姐決定喝什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 34,
    "part": 3,
    "question": "",
    "audio": "sounds/34.mp3",
    "image": "images/34.png",
    "transcript": "男 妳的房間這麼亂，為什麼不整理？\n女 我本來上星期日要整理房間，但是我的經理要我去公司。\n男 那妳今天看了一個下午的書，為什麼不打掃？\n女 好啦！我明天會整理。\n男 請問這位小姐明天打算做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 35,
    "part": 3,
    "question": "",
    "audio": "sounds/35.mp3",
    "image": "images/35.png",
    "transcript": "男 這裡的天氣怎麼樣？\n女 冬天太冷，夏天太熱。\n男 那麼春天呢？\n女 常常下雨。\n男 請問這裡的春天常常怎麼樣？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 36,
    "part": 3,
    "question": "",
    "audio": "sounds/36.mp3",
    "image": "images/36.png",
    "transcript": "男 我想找王先生。\n女 請問您和他約好了嗎？\n男 沒有。是他要我來找他的。\n女 您先留下您的電話，我會請王先生打電話給您。\n男 請問這位小姐要這位先生做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 37,
    "part": 3,
    "question": "",
    "audio": "sounds/37.mp3",
    "image": "images/37.png",
    "transcript": "男 小春的生日快到了，我們一起送他禮物，怎麼樣？\n女 好啊！他喜歡畫畫，我們可以送他畫畫用的筆。\n男 嗯，還可以送他放筆的袋子。\n女 好啊，今天下課以後我們一起去買禮物吧。\n男 請問他們決定送什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 38,
    "part": 3,
    "question": "",
    "audio": "sounds/38.mp3",
    "image": "images/38.png",
    "transcript": "男 妳看電視新聞了嗎？有一個很可怕的消息。\n女 什麼可怕的消息？\n男 妳快點開電視，我剛剛才看到的。\n女 我上網看過新聞了，可是沒看到什麼可怕的消息。\n男 請問這位先生從哪裡知道可怕的消息？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 39,
    "part": 3,
    "question": "",
    "audio": "sounds/39.mp3",
    "image": "images/39.png",
    "transcript": "男 妳想吃什麼?\n女 聽說這裡的北京烤鴨很好吃。\n男 我們點一隻烤鴨，一碗酸辣湯，怎麼樣？\n女 再點一個糖醋魚吧！\n男 請問他們應該在什麼地方？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 40,
    "part": 3,
    "question": "",
    "audio": "sounds/40.mp3",
    "image": "images/40.png",
    "transcript": "男 已經很晚了，妳怎麼還在這裡？\n女 經理說明天要和他一起討論，我今天一定要準備好。\n男 我不放心妳一個人回家，還是等會兒我開車送妳回去。\n女 謝謝你！但是我今天晚上打算睡在公司裡。\n男 請問這位小姐今天晚上打算做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 41,
    "part": 4,
    "question": "",
    "audio": "sounds/41.mp3",
    "image": "",
    "transcript": "男 我昨天運動了一整天。\n女 你看你，累到說不了話了？\n男 喔，不是因為運動，是因為我早上五點就起床了，所以想睡覺。\n女 你這樣沒辦法上班，我幫你請假，你快回去睡吧！\n男 請問這位小姐為什麼要幫這位先生請假？",
    "options": ["（A）因為他想睡覺", "（B）因為他想運動", "（C）因為他不想上班", "（D）因為他起不了床"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 42,
    "part": 4,
    "question": "",
    "audio": "sounds/42.mp3",
    "image": "",
    "transcript": "男 妳上個禮拜的旅行怎麼樣？\n女 還不錯。交通方便、風景漂亮，我想去的地方都去了。\n男 那真是個開心的旅行。\n女 嗯，雖然每件事都不錯，但是我回國的時候，把錢包掉在旅館了。\n男 關於這位小姐，下面哪一個是對的？",
    "options": ["（A）她旅行時不小心掉了東西", "（B）她旅行時有些想去的地方沒去", "（C）她覺得旅行時最麻煩的是交通", "（D）她覺得旅行最重要的是風景漂亮"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 43,
    "part": 4,
    "question": "",
    "audio": "sounds/43.mp3",
    "image": "",
    "transcript": "男 妳怎麼了？好像不太開心的樣子。\n女 我沒事，我每次考試的時候就會這樣。\n男 可是昨天不是已經考完了嗎？\n女 是啊，可是我很擔心沒考好。\n男 這位小姐為什麼不開心？",
    "options": ["（A）她怕考得不好", "（B）她的成績不好", "（C）她沒參加考試", "（D）她怕題目寫不完"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 44,
    "part": 4,
    "question": "",
    "audio": "sounds/44.mp3",
    "image": "",
    "transcript": "女 王先生嗎？您好，我是住在您家樓下的陳太太。\n男 請問有什麼事嗎？\n女 我總是聽到您走路的聲音，有時還聽到您與女朋友大聲地講話。我找您好幾次了，可是您都不在家。\n男 啊！不好意思，不好意思，我會注意的。\n女 陳太太為什麼找王先生？",
    "options": ["（A）想請他搬家", "（B）想請他吃飯", "（C）介紹女朋友給他", "（D）請他注意聲音的大小"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 45,
    "part": 4,
    "question": "",
    "audio": "sounds/45.mp3",
    "image": "",
    "transcript": "男 妳昨天怎麼那麼晚才睡？\n女 我昨天十二點多睡的，我不覺得晚啊！\n男 都半夜了，還不晚？這麼晚才睡覺對身體很不好。\n女 還好吧？我一直都是這個時間睡覺，也沒生什麼病。\n女 請問這位小姐的意思是什麼？",
    "options": ["（A）她習慣在不同的時間睡覺", "（B）她每天都是這個時間起床", "（C）她認為睡覺對健康有影響", "（D）她不覺得自己很晚才睡覺"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/46.mp3",
    "image": "",
    "transcript": "男 夏天到了，我們明天去海邊吧！\n女 好啊！你覺得我應該穿短裙好呢？還是短褲好呢？\n男 我覺得妳應該穿短褲，因為我們要在沙灘上打球。\n女 好啊，明天見。\n女 請問這位先生說了什麼？",
    "options": ["（A）他剛從海邊回來", "（B）他喜歡夏天去海邊玩", "（C）他給這位小姐買了褲子", "（D）他約了這位小姐明天去運動"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/47.mp3",
    "image": "",
    "transcript": "男 為了妳的生日，我想請妳吃蛋糕。\n女 你人來我就很開心了，蛋糕，我來準備就好了。\n男 這是為了感謝妳請我參加明天的生日舞會，或是妳有更想要的禮物嗎？\n女 你太客氣了。吃蛋糕和收禮物都不是最重要的事。\n女 請問這位小姐的意思是什麼？",
    "options": ["（A）她不想請這位先生吃蛋糕", "（B）她想幫這位先生慶祝生日", "（C）她要朋友來參加舞會就好", "（D）她想要大家一起唱生日歌"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/48.mp3",
    "image": "",
    "transcript": "男 我要去逛百貨公司，要一起嗎？\n女 我最近花了太多錢了，還是不要吧。\n男 最近百貨公司有活動，很多商品不但很便宜，還會給很多試用的東西。\n女 喔，有不用花錢的啊！那我們快走吧！\n女 為什麼這位小姐想去百貨公司？",
    "options": ["（A）她想拿商店送的東西", "（B）她最近很想花錢買東西", "（C）她想要這位先生送她禮物", "（D）她想和這位先生一起去逛街"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/49.mp3",
    "image": "",
    "transcript": "男 今天天氣好熱，我們在家吹冷氣多好，還是不要去買衣服了。\n女 不行，你昨天答應我今天要出門買衣服。\n男 可是妳沒發現衣服已經很多了嗎？\n女 我覺得，你只是怕太晚回家，沒辦法看棒球比賽！\n女 請問下面哪一個是對的？",
    "options": ["（A）這位先生今天想留在家裡", "（B）這位小姐怕自己太晚回家", "（C）他們兩人今天都想看棒球比賽", "（D）他們已經買完衣服回家休息了"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/50.mp3",
    "image": "",
    "transcript": "男 小姐，這是昨天跟你們買的牛奶，味道有點奇怪，我想換一瓶新的。\n女 請問您帶了發票嗎？\n男 喔，我沒帶來。\n女 我們要看到發票，才能換東西，不好意思。\n女 這位小姐的意思是什麼？",
    "options": ["（A）她要把錢還給客人", "（B）東西賣出去就不能換了", "（C）她沒有東西可以換給客人", "（D）沒有發票，就不能換東西"],
    "answer": "D",
    "remark": ""
  }
];